#ifndef LED_MAP_H
#define LED_MAP_H

#define TRIANGLE_STRIP_PWM 3
#define TRIANGLE_COUNTER_START 0
#define TRIANGLE_COUNTER_LEN 76
#define TRIANGLE_VERTICAL_START 77
#define TRIANGLE_VERTICAL_LEN 56
#define TRIANGLE_HORIZONTAL_START 133
#define TRIANGLE_HORIZONTAL_LEN 35
#define TRIANGLE_TRIANGLE_START 168
#define TRIANGLE_TRIANGLE_LEN 132
#define TRIANGLE_LED_COUNT 300

#define SHELF_STRIP_PWM 5
#define SHELF_FIRST_VERT_START 0
#define SHELF_FIRST_VERT_LEN 15
#define SHELF_BOTTOM_HORIZ_START 16
#define SHELF_BOTTOM_HORIZ_LEN 77
#define SHELF_SECOND_VERT_START 93
#define SHELF_SECOND_VERT_LEN 8
#define SHELF_MID_HORIZ_START 99
#define SHELF_MID_HORIZ_LEN 77
#define SHELF_THIRD_VERT_START 177
#define SHELF_THIRD_VERT_LEN 33
#define SHELF_TOP_HORIZ_START 209
#define SHELF_TOP_HORIZ_LEN 90
#define SHELF_LED_COUNT 300

#define CIELING_STRIP_PWM 6
#define CIELING_FIRST_VERT_START 0
#define CIELING_FIRST_VERT_LEN 23
#define CIELING_FIRST_HORIZ_START 24
#define CIELING_FIRST_HORIZ_LEN 36
#define CIELING_SECOND_VERT_START 30
#define CIELING_SECOND_VERT_LEN 60
#define CIELING_SECOND_HORIZ_START 120
#define CIELING_SECOND_HORIZ_LEN 44
#define CIELING_SPIRAL_START 164
#define CIELING_SPIRAL_LEN 137
#define CIELING_LED_COUNT 300

#define COUCH_STRIP_PWM 4
#define COUCH_LED_COUNT 300

#endif