#define TRIANGLE_STRIP_PWM 3
#define TRIANGLE_LED_COUNTER_START 0
#define TRIANGLE_LED_COUNTER_LEN 76
#define TRIANGLE_LED_VERTICAL_START 77
#define TRIANGLE_LED_VERTICAL_LEN 56
#define TRIANGLE_LED_HORIZONTAL_START 133
#define TRIANGLE_LED_HORIZONTAL_LEN 35
#define TRIANGLE_LED_TRIANGLE_START 168
#define TRIANGLE_LED_TRIANGLE_LEN 132
#define TRIANGLE_LED_COUNT 300

#define SHELF_STRIP_PWM 5

#define CIELING_STRIP_PWM 6

#define COUCH_STRIP_PWM 4